### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by flaviogf** [flaviogf/pyflunt#2]
# Requirements
- [x] Specific implementations
- [x] Implement

# Implementation

## Notifications
- [x] Notification
- [x] Notifiable
  - [x] add_notification
  - [x] add_notifications
  - [x] add_notifications_from_notifiable
---

## Specifications

---

## Validations
- [x] Contract
- [x] BoolValidationContract
  - [x] is_false
  - [x] is_true
- [x] DateTimeValidationContract
  - [x] is_greater_than
  - [x] is_greater_or_equals_than
  - [x] is_lower_than
  - [x] is_lower_or_equals_than
  - [x] is_between
  - [x] is_none
- [x] NumberValidationContract
  - [x] is_greater_than
  - [x] is_greater_or_equals_than
  - [x] is_lower_than
  - [x] is_lower_or_equals_than
  - [x] are_equals
  - [x] are_not_equals
  - [x] is_between
  - [x] is_none
- [x] UUIDValidationContract
  - [x] are_equals
  - [x] are_not_equals
  - [x] is_empty
  - [x] is_not_empty
- [x] StringValidationContract
  - [x] is_empty
  - [x] is_not_empty
  - [x] is_not_none_or_empty
  - [x] is_not_none_or_white_space
  - [x] is_none_or_empty
  - [x] has_min_len
  - [x] has_max_len
  - [x] has_len
  - [x] contains
  - [x] are_equals
  - [x] are_not_equals
  - [x] is_email
  - [x] is_email_or_empty
  - [x] is_url
  - [x] is_url_or_empty
  - [x] matchs
  - [x] is_digit
  - [x] has_min_length_if_not_none_or_empty
  - [x] has_max_length_if_not_none_or_empty
  - [x] has_exact_length_if_not_none_or_empty
- [x] TimeDeltaValidationContract
  - [x] is_greater_than
  - [x] is_greater_or_equals_than
  - [x] is_lower_than
  - [x] is_lower_or_equals_than
  - [x] is_between
  - [x] is_none
---

**Comment by flaviogf** [comment]
1.0.0
